<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/15
 * Time: 14:56
 */

namespace app\userapi\model;


use app\common\model\Base;

class Admin extends Base
{

    public function initialize()
    {
        // todo
        parent::initialize(); // TODO: Change the autogenerated stub
    }





}