<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/26
 * Time: 10:18
 */

namespace app\adminall\model;


use think\Db;

class Order extends Admin
{
    public $_table_title = [
            'address_username'=>'联系方式',
            'address_id'=>'配送地址',
            'pre_delivery_time'=>'预计到达时间',
            'status'=>'订单状态',
            'action'=>'操作',
        ];

    public function fromTypeSelectValues($n,$data)
    {
        return null;
    }

    public function initialize()
    {
        $this->tpl = 'order_list';
        parent::initialize(); // TODO: Change the autogenerated stub
    }

    public function getAddressUsernameAttr($val,$data)
    {
        $name = Db::name('address')->where('id',$data['address_id'])->value('name');
        $phone = Db::name('address')->where('id',$data['address_id'])->value('phone');
        return $name.'&nbsp;&nbsp;'.$phone;
    }

    public function getAddressIdAttr($val,$data)
    {
        return Db::name('address')->where('id',$data['address_id'])->value('address');
    }

    public function getShopIdAttr($val,$data)
    {
        return Db::name('shop')->where('id',$val)->value('shop_name');
    }

    public function getPreDeliveryTimeAttr($val)
    {
        return date('Y-m-d H:i',$val);
    }

    public function getStatusAttr($val)
    {
        $list = config('status.order_sta');
        return $list[$val];
    }

}