<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/12
 * Time: 9:48
 */

namespace app\adminall\model;


use think\Db;

class ShopAuth extends Admin
{
    public $name = 'shop';

    public $search_time = 'register_time';
    public $search_field = 'id|shop_name|contacts|contacts_phone';

    public $_table_title=[
        'id'=>'ID',
        'logo'=>'商户LOGO',
        'shop_name'=>'店铺名称',
        'shop_type'=>'店铺分类',
        'contacts'=>'联系人',
        'contacts_phone'=>'联系人电话',
        'register_time'=>'申请时间',
        'examine_status'=>'状态',
        'action'=>'操作',
    ];

    public function fromTypeSelectValues($n,$data)
    {
        return null;
    }

    public function whereCopy($field = '', $value = [])
    {
        $field = 'examine_status';
        $value = [['neq',config('status.true')]];
        return parent::whereCopy($field, $value); // TODO: Change the autogenerated stub
    }


    public function getLogoAttr($val)
    {
        return '<img src="'.$val.'" width="20px"/>';
    }

    public function getRegisterTimeAttr($val)
    {
        return date('Y-m-d H:i',$val?:0);
    }

    public function getShopTypeAttr($val)
    {
        return Db::name('shop_businesstype')->where('id',$val)->value('typename');
    }

    public function getExamineStatusAttr($val)
    {
        if ($val == config('status.wait')){
            return '<p style="color: #0e9aef; font-size: 14px">待审核</p>';
        }elseif ($val == config('status.true')){
            return '<p style="color: #0e9aef; font-size: 14px">审核通过</p>';
        }elseif ($val == config('status.false')){
            return '<p style="color: #0e9aef; font-size: 14px">审核失败</p>';
        }else{
            return '<p style="color: #0e9aef; font-size: 14px">没有审核</p>';
        }
    }

    public function getAddressAttr($val,$data)
    {
        $info = Db::name('shop_address')->where('shopid',$data['id'])->find();
        return $info['sheng'].' '.$info['shi'].' '.$info['qu'].' '.$info['shop_address'];
    }

    public function getBusinessHoursAttr($val,$data)
    {
        if (strpos($val,'-')){
            return explode('-',$val);
        }else{
            return ['',''];
        }
    }


    public function getShopTypeValAttr($val,$data)
    {
        $name = Db::name('shop_businesstype')->where('id',$data['shop_type'])->find();
        $title = Db::name('shop_businesstype')->where('id',$name['pid'])->find();
        $top = Db::name('shop_type')->where('id',$title['shop_type'])->find();
        $list['name'] = $name['typename'];
        $list['title'] = $title['typename'];
        $list['top'] = $top['typename'];
        return $list;
    }

}