<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/7
 * Time: 10:16
 */

namespace app\adminall\model;


class TakeMoneyWait extends TakeMoneyAll
{
    protected $updateTime = 'up_time';

    public $_table_title = [
        'id' => '提现编号',
        'uid' => '提现人id【名称】',
        'identity' => '提现人id身份',
        'bank_account' => '提现账户',
        'money' => '提现金额',
        'up_time' => '审核时间',
        'action' => '操作',
    ];

    public function whereCopy($field = '', $value = [])
    {
        $field = 'status';
        $value = [2];
        return parent::whereCopy($field, $value); // TODO: Change the autogenerated stub
    }


}