<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/8/4
 * Time: 15:46
 */

namespace app\adminall\model;


use think\Db;

class UserMoneyLog extends Admin
{
    public $name = 'user_pay_log';

    protected $autoWriteTimestamp =true;

    protected $createTime = 'add_time';

    protected $updateTime = false;

    public $_table_title = [
        'user_id' => 'UID',
        'user_name' => '用户名',
        'user_phone' => '手机号',
        'type' => '类型',
        'money' => '收支',
        'content' => '说明',
        'add_time' => '日期',
    ];

    public function getUserNameAttr($val,$data)
    {
        $name = Db::name('user')->where('id',$data['user_id'])->value('nickname');
        return $name?:"";
    }

    public function getUserPhoneAttr($val,$data)
    {
        $n = Db::name('user')->where('id',$data['user_id'])->value('phone');
        return $n?:"";
    }

    public function getContentAttr($val,$data)
    {
        $str = '支付外卖订单(单号：'.$data['order_num'].')';
        return $str;
    }

    public function whereCopy($field = '', $value = [])
    {
        return parent::whereCopy($field, $value); // TODO: Change the autogenerated stub
    }
}