<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/15
 * Time: 15:30
 */

namespace app\userapi\controller;

use think\Db;
use think\Exception;
use think\Loader;
use think\Request;

class Address extends Api
{

    public function _initialize()
    {
        $this->model = Loader::model('Address');
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 收货地址列表 我的
     * @param Request $request
     * @return mixed
     */
    public function indexList(Request $request)
    {
        if ($request->isGet()) {
            $id = $request->get('id');
            if (empty($id)) {
                return message('', '参数错误', 1);
            }
            try {
                $list = $this->model->selectAllTree('user_id', [['eq', $id]],'isdefault desc');
            } catch (\Exception $e) {
                return message('', $e->getMessage(), 5);
            }
            if (empty($list)) {
                return message('', '您还没有收货地址', 4);
            } else {
                return message($list, '成功', 2);
            }
        }
    }

    /**
     * 新增收货地址
     * @param Request $request
     * @return mixed
     */
    public function addressAddMe(Request $request)
    {
        $model = new \app\userapi\model\Address();
        $vali = Loader::validate('Address');
        if ($request->isPost()){
            $data['name'] = $request->post('name');
            $data['sex'] = $request->post('sex');
            $data['phone'] = $request->post('phone');
            $data['address'] = $request->post('address');
            $data['building_card'] = $request->post('building_card');
            $data['label'] = $request->post('label');
            $data['user_id'] = $request->post('id');
            $data['jd'] = $request->post('jd');
            $data['wd'] = $request->post('wd');
            $data['sheng'] = $request->post('sh');
            $data['shi'] = $request->post('shi');
            $data['qu'] = $request->post('q');
            if (!$vali->scene('AddList')->check($data)){
                return message('',$vali->getError(),1);
            }
            try{
                $id = $model->insertGetId($data);
            }catch (\Exception $e){
                return message('',$e->getMessage(),5);
            }
            if (empty($id)){
                return message('','新增失败',1);
            }else{
                return message($id,'新增成功',2);
            }
        }
    }

    public function setStatus(Request $request, $model = '', $script = false, $value = '')
    {
        $model = 'Address';
        if ($request->post('status') == 'deft'){   //修改默认地址
            $_POST['id'] = $request->post('id/d');
            $_POST['status'] = 'all-purpose';
            $_POST['field'] = "isdefault";
            $request = Request::create($request->url(),'POST',$_POST);
            $info = Db::name($model)->where('id',$request->post('id/d'))->find();
            Db::name($model)->where('user_id',$info['user_id'])->where($_POST['field'],1)
                ->setField($_POST['field'],0);
            $value = 1;
        }
        return parent::setStatus($request, $model, $script, $value = ''); // TODO: Change the autogenerated stub
    }

}