<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/7/10
 * Time: 18:22
 */

namespace app\userapi\controller;


use app\userapi\validate\Bank;
use think\Db;
use think\Loader;
use think\Request;

class BankCard extends Api
{
    /**
     *  用户银行卡列表
     */
    public function index(Request $request)
    {
        $model = Loader::model('BankCard');
        if ($request->isGet()){
            $uid = $request->get('uid/d');
            try{
                $list = $model->field('identity',true)->where('uid',$uid)->where('identity',1)->select();
            }catch (\Exception $e){
                return message('',$e->getMessage(),5);
            }
            if (empty($list)) {
                return message('', '获取失败', 3);
            }else{
                return message($list, '获取成功', 2);
            }
        }
    }

    /**
     * 银行卡操作
     */
    public function save(Request $request)
    {
        $vali = new Bank();
        if ($request->isPost()){
            $data = $request->post();
            if (!$vali->scene('add')->check($data)){
                return message('',$vali->getError(),1);
            }
            try{
                $n = Db::name('bank_card')->insertGetId($data);
            }catch (\Exception $e){
                return message('',$e->getMessage(),5);
            }
            if (empty($n)) {
                return message('', '添加失败', 3);
            }else{
                return message('', '添加成功', 2);
            }
        }
    }
    public function setStatus(Request $request, $model = '', $script = false)
    {
        $model = 'bank_card';
        return parent::setStatus($request, $model, $script); // TODO: Change the autogenerated stub
    }

}