<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/20
 * Time: 15:38
 */

namespace app\userapi\controller;


use app\userapi\model\ShopCollect;
use think\Db;
use think\Loader;
use think\Request;

class Collect extends Api
{
    /**
     * 我的/收藏
     * @param Request $request
     * @return mixed
     */
    public function indexList(Request $request)
    {
        $model = new ShopCollect();
        if ($request->isGet()){
            $id = $request->get('id');
            try{
                $info = $model->getModelList($id);
            }catch (\Exception $e){
                return message('',$e->getMessage(),5);
            }
            if (empty($info)){
                return message('','获取失败',3);
            }else{
                return message($info,'获取成功',2);
            }
        }
    }


    public function setStatus(Request $request, $model = '', $script = false, $value='')
    {
        $model = 'ShopCollect';
        return parent::setStatus($request, $model, $script, $value=''); // TODO: Change the autogenerated stub
    }


}