<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/20
 * Time: 11:02
 */

namespace app\userapi\controller;


use app\userapi\model\OrderComment;
use think\Config;
use think\Db;
use think\Loader;
use think\Request;

class TakeShopAbout extends Api
{
    public function _initialize()
    {
        $this->model = new OrderComment();
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    /**
     * 评论  我的
     * @param Request $request
     * @return mixed
     */
    public function indexList(Request $request,$t='')
    {
        if ($request->isGet()){
            $id = $request->get('id');
            $img = $request->get('img_num',0);  //有图评论
            $gid = $request->get('gid',0);  //商品id
            $field = $t?'oc.sid':'oc.uid';
            $img_op = $img?'':'0';
            $gid_op = $gid?'eq':'neq';
            try{
//                 order_goods field as og.id og_id,og.order_id og_order_id,og.goods_id og_goods_id,og.num og_num,
//                                      og.price og_price,og.sale og_sale,og.total og_total
                $info = $this->model->alias('oc')->field('oc.*,og.order_id og_order_id,
                                      og.goods_id og_goods_id,og.num og_num,
                                      og.price og_price,og.sale og_sale,og.total og_total')
                    ->join('db_order_goods og','og.order_id=oc.order_id')
                    ->where($field,$id)
                    ->where('oc.imgurl','neq',$img_op)
                    ->where('og.goods_id',$gid_op,$gid)
                    ->order('oc.id','desc')
                    ->select();
                if (empty($info)){
                    $list = [];
                }else {
                    foreach ($info as $value) {
                        $value['username'] = $value->userinfo->nickname;
                        $value['userimg'] = $value->userinfo->head_img?$value->userinfo->head_img:
                            Config::get('system.site_url').Config::get('system.user_img');
                        $value['shop_name'] = $value->shop_name;
                        $value['shop_img'] = $value->shop_img;
                        $value['goods_img'] = $value->goods_img;
                        $value['goods_name'] = $value->goods_name;
                        $value['time_num'] = $value->time_num;
                        $value['revert'] = $value->revert;
                        unset($value['userinfo']);
                        $list[] = $value->toArray();
                    }
                }
            }catch (\Exception $e){
                return message('',$e->getMessage(),5);
            }

            if (empty($list)){
                return message('','获取失败',3);
            }else{
                return message($list,'获取成功',2);
            }
        }
    }

    public function setStatus(Request $request, $model = '', $script = false, $value = '')
    {
        $model = 'OrderComment';
        if ($request->post('status') == 'del'){
            Db::name('reply')->where('reply_id',$request->post('id/d'))->delete();
        }
        return parent::setStatus($request, $model, $script, $value); // TODO: Change the autogenerated stub
    }
}