<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/20
 * Time: 15:35
 */

namespace app\userapi\controller;


use app\userapi\model\ShopVisitor;
use think\Db;
use think\Loader;
use think\Log;
use think\Request;

class Track extends Api
{
    /**
     * 足迹 我的
     * @param Request $request
     * @return mixed
     */
    public function indexList(Request $request)
    {
        $model = new ShopVisitor();
        if ($request->isGet()){
            $id = $request->get('id');
            try{
                $list = $model->shopListAll($id);
            }catch (\Exception $e){
                return message('',$e->getMessage(),5);
            }
            if (empty($list)){
                return message('','获取失败',3);
            }else{
                return message($list,'获取成功',2);
            }
        }
    }


    public function setStatus(Request $request, $model = '', $script = false, $value = '')
    {
        $model = 'ShopVisitor';
        if ($request->post('status') == 'del'){
            $id = Db::name('shop_visitor')->where('shopid',$request->post('id'))->value('id');
            $_POST['id'] = $id;
            $_POST['status'] = 'del';
            $request = Request::create($request->url(),'POST',$_POST);
        }
        return parent::setStatus($request, $model, $script, $value); // TODO: Change the autogenerated stub
    }

}