<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/5/18
 * Time: 10:22
 */

namespace app\adminall\controller;

use think\Request;
use think\Loader;

/**
 * 商家评价
 * Class OrderComment
 * @package app\adminall\controller
 */
class OrderComment extends Admin
{
    public function index(Request $request)
    {
        $_from_data = [];
        $model = Loader::model($this->model_name);
        //分页
        $where = $model->laypageWhere($request);
        $data = $model->selectList($where->index_where['field'],$where->index_where['value'],[$where->index_curr,$where->index_size]);
        //
        foreach ($data as $val){
            $val['shop_name'] = $val->shop_name;
            $val['user_name'] = $val->user_name;
            $val['distribution'] = $val->riderInfo?$val->riderInfo->evaluate:'';
            $_from_data[] = $val->toArray();
        }
        $_table_title = [
            'id'=>'评论ID',
            'shop_name'=>'商家名称[ID]',
            'user_name'=>'顾客[ID]',
            'order_id'=>'订单ID',
            'num'=>'综合评星',
            'distribution'=>'配送',
            'content'=>'评价内容',
            'add_time'=>'时间',
            'action'=>'操作',
        ];
        /**
         * 分页参数
         */
        //分页上传的地址
        $this->assign('index_url',$_SERVER['PATH_INFO']);
        //分页的总数
        $this->assign('index_count',$where->index_count);
        //分页的页码
        $this->assign('index_curr',$where->index_curr);
        //分页的每页数量
        $this->assign('index_size',$where->index_size);
        /**
         * 分页参数
         */
        return Tpldemo::temp()->tableData($_from_data)
            ->tableTitle($_table_title)->templateLists()->templateView();
    }

    public function setStatus(Request $request, $model = '', $script = false)
    {
        if (empty($model)){
            $model=$request->controller();
        }
        return parent::setStatus($request, $model, $script); // TODO: Change the autogenerated stub
    }


}