<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/6/12
 * Time: 14:59
 */

namespace app\adminall\controller;


use think\Db;
use think\Loader;
use think\Request;

class ShopAuth extends Admin
{
    public function show(Request $request)
    {
        $model = Loader::model($this->model_name);
        if ($request->isAjax())
        {
            return 'is ajax';
        }else{
            $id = $request->get('id');
            $info = $model::get($id);
            $list = [];
            $list['shop_name'] = $info['shop_name'];
            $list['contacts'] = $info['contacts'];
            $list['contacts_phone'] = $info['contacts_phone'];
            $list['shop_phone'] = $info['shop_phone'];
            $list['shop_type'] = $info->shop_type_val;
            $list['business_hours'] = $info['business_hours'];
            $list['address'] = $info->address;
            $list['out_img'] = $info['out_img'];
            $list['in_img'] = $info['in_img'];
            $list['logo'] = $info['logo'];
            $this->assign('shop_info',$list);
            //身份证
            $iden_card = Loader::model('ShopCard')->where('shop_id',$id)->where('card_type',2)->find();
            //营业执照
            $shop_idf_card = Loader::model('ShopCard')->where('shop_id',$id)->where('card_type',1)->find();
            //许可证
            $one_card = Loader::model('ShopCard')->where('shop_id',$id)->where('card_type',3)->find();
            //特许证件
            $special_card = Loader::model('ShopCard')->where('shop_id',$id)->where('card_type',4)->find();
            $this->assign('iden_card',$iden_card);
            $this->assign('shop_idf_card',$shop_idf_card);
            $this->assign('one_card',$one_card);
            $this->assign('special_card',$special_card);
            //银行卡信息
            $bank_info = Loader::model('BankCard')->where('uid',$id)->where('identity',3)->find();
            $this->assign('bank_info',$bank_info);

            return Tpldemo::temp()->template('shop_content')->templateView();
        }
    }



    public function setStatus(Request $request, $model = '', $script = false)
    {
        $model = 'Shop';
        return parent::setStatus($request, $model, $script); // TODO: Change the autogenerated stub
    }

}