<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/17
 * Time: 11:11
 */

namespace app\admin\controller;

use app\common\controller\ApiCommon;
use think\Db;
use think\Loader;
use think\Request;

/**
 * 用户组控制器
 * Class AuthGroup
 * @package app\admin\controller
 */
class AuthGroup extends Admin
{
    /**
     * 列表
     * @param Request $request
     * @return mixed
     */
    public function index(Request $request)
    {
        $_from_data = [];
        $model = Loader::model($this->model_name);
        //分页
        $where = $model->laypageWhere($request);
        $index_url = url('index');
        $data = $model->selectList($where->index_where['field'],$where->index_where['value'],[$where->index_curr,$where->index_size]);
        //
        foreach ($data as $val){
            $_from_data[] = $val->toArray();
        }
        $_table_title = [
            ['id'=>'编号'],
            ['title'=>'用户组名称'],
            ['status'=>'状态'],
            ['action'=>'操作'],
        ];
        /**
         * 分页参数
         */
        //分页上传的地址
        $this->assign('index_url',$index_url);
        //分页的总数
        $this->assign('index_count',$where->index_count);
        //分页的页码
        $this->assign('index_curr',$where->index_curr);
        //分页的每页数量
        $this->assign('index_size',$where->index_size);
        /**
         * 分页参数
         */
        return Tpldemo::temp()->tableData($_from_data)
            ->tableTitle($_table_title)->templateLists()->templateView();

    }

    /**
     * 新增和修改
     * @param Request $request
     */
    public function save(Request $request)
    {
        $model = Loader::model($this->model_name);
        if ($request->isAjax()){
            $id = $request->post('id');
            $data = $request->post();
            $vali = Loader::validate('common/AuthGroup');
            if (empty($id)){//新增
                $con = '新增';
                if (!$vali->scene('add')->check($data)){
                    return $this->result('',config('code.no'),$vali->getError());
                }
            }else{//修改
                $con = '修改';
                if (!$vali->scene('edit')->check($data)){
                    return $this->result('',config('code.no'),$vali->getError());
                }
            }
            $res = $model->tabAdd($data,$id);
            if (!empty($res)){
                return $this->result($res,config('code.yes'),$con.'成功');
            }else{
                return $this->result($res,config('code.no'),$con.'失败');
            }
        }else {
            $id = $request->get('id');
            if (!empty($id)){
                $info = $model::get($id);
                $list = $info->toArray();
                $this->assign('data',$list);
            }

            $select['auth_type_id']=config('auth.type_list');
            $this->assign('select',$select);

            Tpldemo::temp()->_from_action = $this->_from_action;
            Tpldemo::temp()
                ->tableData('用户组中文名称','title','请填写中文',1)
                ->tableData('用户组类型','auth_type_id','请填写中文',1,'select');
            return Tpldemo::temp()->templateFrom()->templateView();
        }
    }

    /**
     * 权限分配
     * @param Request $request
     * @return mixed
     * @throws \think\exception\DbException
     */
    public function right(Request $request)
    {
        $model = Loader::model($this->model_name);
        if ($request->isAjax()){
            $id = $request->post('id');
            $data = $request->post();
            $this->tabSave($id,$data,'rightadd','rightedit');
        }else {
            $id = $request->get('id');
            if (!empty($id)){
                $info = $model::get($id);
                $list = $info->toArray();
                $this->assign('data',$list);
            }
            /**
             * 菜单权限分配
             */
            $admin_menu = \app\common\model\AuthRule::all();
            $admin_menu_list = $this->dataListTo($admin_menu);
            $_menu_tree['rules'] = ApiCommon::temp()->arrayTree($admin_menu_list);
            $this->assign('checkbox',$_menu_tree);

            Tpldemo::temp()->_from_action = url('AuthGroup/right');
            Tpldemo::temp()
                ->tableData('勾选规则','rules','请勾选要添加的规则',1,'checkbox');
            return Tpldemo::temp()->templateFrom()->templateView();
        }
    }

    /**
     * 删除 、禁止和开启
     * @param Request $request
     * @param string $model
     * @param bool $script
     * @return mixed
     * @throws \think\Exception
     * @throws \think\exception\PDOException
     */
    public function setStatus(Request $request, $model = '', $script = false)
    {
        $model= $request->controller();
        return parent::setStatus($request, $model, $script); // TODO: Change the autogenerated stub
    }
}