<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/2/6
 * Time: 17:29
 */

namespace app\admin\controller;

use app\common\controller\ApiCommon;
use think\Request;
use think\Loader;
use think\Db;

class AuthMenu extends Admin
{
    protected $model_name = 'common/AuthMenu';
    protected $model_save = 'save';
    protected $model_stat = 'setStatus';
    protected $_from_action;
//    public function _initialize()
//    {
//        $request = Request::instance();
//        $where = $request->controller().'/index';
//        $admin_menu = Loader::model('common/AdminMenu');
//        $name = $admin_menu->where('url','eq',$where)->find();
//        $pname = $admin_menu->where('id','eq',$name['pid'])->value('title');
//        Tpldemo::temp()->_template_title = $name['title'];
//        Tpldemo::temp()->_template_nav = $pname;
//        $this->_from_action = url($this->model_save);
//        $this->model_name = 'common/'.$request->controller();
//        parent::_initialize(); // TODO: Change the autogenerated stub
//    }

    public function index(Request $request)
    {
        $_model_list = [];
        $model = Loader::model($this->model_name);
        //分页
        $where = $model->laypageWhere($request);
        $index_url = url('index');
        $data = $model->selectList($where->index_where['field'],$where->index_where['value'],[$where->index_curr,$where->index_size]);
        //
        foreach ($data as $val){
            $value = $val->toArray();
            $value['type_name'] = $val->type_name;
            $value['user_name'] = $val->user_name;
            $_model_list[] = $value;
        }
        $_table_title = [
            ['id'=>'编号'],
            ['type_name'=>'类型名称'],
            ['user_name'=>'用户名称'],
            ['action'=>'操作']
        ];
        $_from_button = [
            ['menu_title' => '添加菜单', 'from_url' => $this->_from_action, 'ico' => '&#xe600;']
        ];
        $replenish = "edit,del";
        $argument = [$this->_from_action,url($this->model_stat)];

        /**
         * 分页参数
         */
        //分页上传的地址
        $this->assign('index_url',$index_url);
        //分页的总数
        $this->assign('index_count',$where->index_count);
        //分页的页码
        $this->assign('index_curr',$where->index_curr);
        //分页的每页数量
        $this->assign('index_size',$where->index_size);
        /**
         * 分页参数
         */
        Tpldemo::temp()->templateLists();
//        Tpldemo::temp()->_template_title = '菜单分配管理';
        Tpldemo::temp()->_from_button = $_from_button;
        return Tpldemo::temp()->tableData($_model_list,$replenish,$argument)
            ->tableTitle($_table_title)->templateView();
    }

    public function save(Request $request)
    {
        $model = Loader::model($this->model_name);
        if ($request->isAjax()){
            $id = $request->post('id');
            $data = $request->post();
            $vali = Loader::validate($this->model_name);
            if (empty($id)){//新增
                $con = '新增';
                if (!$vali->scene('add')->check($data)){
                    return $this->result('',config('code.no'),$vali->getError());
                }
            }else{//修改
                $con = '修改';
                if (!$vali->scene('edit')->check($data)){
                    return $this->result('',config('code.no'),$vali->getError());
                }
            }
            //halt($data);
            $res = $model->tabAdd($data,$id);
            if (!empty($res)){
                return $this->result($res,config('code.yes'),$con.'成功');
            }else{
                return $this->result($res,config('code.no'),$con.'失败');
            }
        }else{
            $id = $request->get('id');
            if (!empty($id)){
                $info = $model::get($id);
                $list = $info->toArray();
                $this->assign('data',$list);
            }

            /**
             * 菜单权限分配
             */
            $admin_menu = \app\common\model\AdminMenu::all(['menu'=>['in',[1,2,3]]]);
            $admin_menu_list = $this->dataListTo($admin_menu);
            $_menu_tree['menu'] = ApiCommon::temp()->arrayTree($admin_menu_list);
            $this->assign('checkbox',$_menu_tree);

            /**
             * select参数
             */
            //类型
            $select['type_id'] = config('auth.type_list');
            //用户
            $select['user_id'] = Db::name('AuthAdmin')->field('id,username title')
                ->where('status','eq',1)->select();
            $this->assign('select',$select);
            $this->assign('select_field','type_id');

            //模板
            Tpldemo::temp()->_from_action = $this->_from_action;
            Tpldemo::temp()
                ->tableData('类型','type_id','请选择标题',1,'select')
                ->tableData('管理员列表','user_id','请选择管理员',1,'select')
                ->tableData('菜单列表','menu','请选择菜单列表',1,'checkbox');
            return Tpldemo::temp()->templateFrom()->templateView();
        }
    }


    public function setStatus(Request $request, $model = '', $script = false)
    {
        if (empty($model)) {
            $model = 'AuthMenu';
        }
        return parent::setStatus($request, $model, $script); // TODO: Change the autogenerated stub
    }

}