<?php
/**
 * Created by PhpStorm.
 * User: Administrator
 * Date: 2018/1/17
 * Time: 11:11
 */

namespace app\admin\controller;

use think\Db;
use think\Loader;
use think\Request;

class AuthAdmin extends Admin
{
    protected $model_name = 'AuthAdmin';
    public function _initialize()
    {
        Tpldemo::temp()->_template_nav = '管理员管理';
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index(Request $request)
    {
        $_from_data = [];
        $model = Loader::model($this->model_name);
        //分页
        $where = $model->laypageWhere($request);
        $index_url = url('index');
        $data = $model->selectList($where->index_where['field'],$where->index_where['value'],[$where->index_curr,$where->index_size]);
        //
        foreach ($data as $val){
            $_from_data[] = $val->toArray();
        }
        $_table_title = [
            ['id'=>'编号'],
            ['username'=>'管理员账号'],
            ['status'=>'状态'],
            ['action'=>'操作'],
        ];
//        $replenish = 'status,edit,addrule,del';
//        $argument = [url('AuthAdmin/SetStatus'),url('AuthAdmin/Save'),url('AuthAdmin/groupType'),url('AuthAdmin/SetStatus')];
        $_from_action = url('AuthAdmin/save');
        $_from_button = [
            ['menu_title' => '添加管理员', 'from_url' => $_from_action, 'ico' => '&#xe600;']
        ];
        /**
         * 分页参数
         */
        //分页上传的地址
        $this->assign('index_url',$index_url);
        //分页的总数
        $this->assign('index_count',$where->index_count);
        //分页的页码
        $this->assign('index_curr',$where->index_curr);
        //分页的每页数量
        $this->assign('index_size',$where->index_size);
        /**
         * 分页参数
         */
        Tpldemo::temp()->_template_title = '管理员列表';
        Tpldemo::temp()->_from_button = $_from_button;
        return Tpldemo::temp()->tableData($_from_data,'','')
            ->tableTitle($_table_title)->templateLists()->templateView();

    }

    public function save(Request $request)
    {
        $model = Loader::model($this->model_name);
        if ($request->isPost()){
            $id = $request->post('id');
            $data = $request->post();
            $vali = Loader::validate($this->model_name);
            if (empty($id)){//新增
                $con = '新增';
                if (!$vali->scene('add')->check($data)){
                    return $this->result('',config('code.no'),$vali->getError());
                }
            }else{//修改
                $con = '修改';
                if (!$vali->scene('edit')->check($data)){
                    return $this->result('',config('code.no'),$vali->getError());
                }
            }
            $res = $model->tabAdd($data,$id);
            if (!empty($res)){
                return $this->result($res,config('code.yes'),$con.'成功');
            }else{
                return $this->result($res,config('code.no'),$con.'失败');
            }
        }else{
            $id = $request->get('id');
            if (!empty($id)){
                $info = $model::get($id);
                $list = $info->toArray();
                $this->assign('data',$list);
            }
            $_from_action = url('AuthAdmin/save');
            Tpldemo::temp()->_from_action = $_from_action;
            Tpldemo::temp()
                ->tableData('管理员账号','username','请填写字母和数字，下划线_及破折号-',1)
                ->tableData('管理员密码','password','请填写字母和数字，下划线_及破折号-',1,'password')
                ->tableData('管理员简介','text','请填写不超过100个字符',0,'textarea');
            return Tpldemo::temp()->templateFrom()->templateView();
        }
    }

    /**
     * 给管理员分配用户组
     * @param Request $request
     * @throws \think\db\exception\DataNotFoundException
     * @throws \think\db\exception\ModelNotFoundException
     * @throws \think\exception\DbException
     */
    public function groupType(Request $request)
    {
        $model = Loader::model('AuthGroupAccess');
        if ($request->isAjax()){
            $data = $request->post();
            $id = $request->post('id');
            //转换为添加数据格式
            $list = $model->infoData($id,$data['group_id']);
            $res = $model->saveAll($list);
            if (!empty($res)){
                return $this->result($res,config('code.yes'),'成功');
            }else{
                return $this->result($res,config('code.no'),'失败');
            }
        }else {
            $list['id'] = $request->get('id');
            $list['group_id'] = Db::name('AuthGroupAccess')->where(['uid'=>$list['id']])->column('group_id');
            $this->assign('data',$list);

            /**
             * 复选框
             */
            $right = Db::name('AuthGroup')->field('id,title')
                ->where('status','eq',1)->where('auth_type_id',1)->select();
            $this->assign('right',$right);

            Tpldemo::temp()->_from_action = url('groupType');
            Tpldemo::temp()
                ->tableData('用户组列表','group_id','请勾选要添加的用户组',1,'right');
            return Tpldemo::temp()->templateFrom()->templateView();
        }
    }

    public function setStatus(Request $request, $model = '', $script = false)
    {
        $model = $this->model_name;
        return parent::setStatus($request, $model, $script); // TODO: Change the autogenerated stub
    }

}