<?php
namespace app\admin\controller;

use think\Loader;
use think\Session;

class Index extends Admin
{
    public function _initialize()
    {
        parent::_initialize(); // TODO: Change the autogenerated stub
    }

    public function index()
    {
//        halt(Session::has('name'));
        if (!Session::has('name')){
            $this->logout();
        }
        return $this->fetch('index/index');
    }

    public function logout ()
    {
        if (Session::has('name')) {
            $list = [
                1 => ['url' => 'admin/index/index', 'value' => []],
                2 => ['url' => 'admin/extro_index/index', 'value' => ['name' => 'agent']],
                3 => ['url' => 'admin/extro_index/index', 'value' => ['name' => 'city']],
                4 => ['url' => 'admin/extro_index/index', 'value' => ['name' => 'area']],
            ];
            $id = Session::get('auth_type_id');

            //清除session 并跳转登录
            Session::clear();
            $this->redirect($list[$id]['url'], $list[$id]['value']);
        }else {
            Session::clear();
            $this->redirect('Admin/Login/index');
        }
    }

    public function welcome()
    {
//        halt(12312);
        $system['system_money'] = Loader::model('admin')->systemMoney();
        $this->assign('system',$system);
        return $this->fetch('index/welcome');
    }
}
